{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "controller.serviceAccountName" . }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
{{- end }}
