apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: my-repo-creds
  type: git
  url: git@github.com:nitinpahwa77/devops.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----


---

apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo-app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
    name: my-repo-ap-cred
    type: git
    url: git@github.com:nitinpahwa77/argocd-demoapp-nitin.git
    sshPrivateKey: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACAr3S3NTsRGycuhyuDfMSCawdKsyODEvOUySbG4/5xevgAAAKAMQpe3DEKX
      twAAAAtzc2gtZWQyNTUxOQAAACAr3S3NTsRGycuhyuDfMSCawdKsyODEvOUySbG4/5xevg
      AAAEDYgnp2tSFjIp7+U0TJwns1XkPO5lDhVZWHSFdv232anivdLc1OxEbJy6HK4N8xIJrB
      0qzI4MS85TJJsbj/nF6+AAAAFm5pdGlucGFod2E3N0BnbWFpbC5jb20BAgMEBQYH
      -----END OPENSSH PRIVATE KEY-----




