apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync
  namespace: reloader-test
spec:
  vault: 
    name: aksssswe3bv-kv # name of key vault
    object:
      name: pvtsshkeya23w2zure # name of the akv secret object that we created using az command
      type: secret # akv object type / can also be keys or certificates
  output: 
    secret: 
      name: poduseme # kubernetes secret name that we want to see in k8s
      dataKey: secret-value # key to store object value in kubernetes secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: reloader-test
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mypod
        image: redis
        volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: poduseme #secret that we sync with akv2k8s in line 14
          optional: true
