apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Devops-coach-js/LAS-DMP.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAH9UknvaJdLP2A+kg114Q+PWGt5rss+c1vc2mbaX9jzgAAAKCRXpuPkV6b
    jwAAAAtzc2gtZWQyNTUxOQAAACAH9UknvaJdLP2A+kg114Q+PWGt5rss+c1vc2mbaX9jzg
    AAAEA0v5M1QCQKDOZYZbg8WDltC3ir/ATun7GUVQguK68EJQf1SSe9ol0s/YD6SDXXhD49
    Ya3muyz5zW9zaZtpf2POAAAAFm5pdGlucGFod2E3N0BnbWFpbC5jb20BAgMEBQYH
    -----END OPENSSH PRIVATE KEY-----